## traefik.yml

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

# Docker configuration backend

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

#http:
#  routers:
#    http-catchall:
#      rule: hostregexp(`{host:.+}`)
#      entrypoints:
#      - http
#      middlewares:
#      - redirect-to-https
#  middlewares:
#    redirect-to-https:
#      redirectScheme:
#        scheme: https
#        permanent: false

# API and dashboard configuration
api:
  insecure: true

